// SPDX-License-Identifier: BSD-3-Clause
// Copyright Contributors to the OpenColorIO Project.

//! Committed fixtures, generated by the oracle and locked by `fixtures/MANIFEST.toml`.
//!
//! Only `cargo xtask oracle regen` writes fixtures and the manifest. Every read checks the
//! file's SHA-256 against the manifest, so a fixture edited by hand fails every test that
//! uses it.

use std::collections::BTreeMap;
use std::sync::OnceLock;

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::paths;

/// The fixture manifest (`fixtures/MANIFEST.toml`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Manifest {
    /// What generated the fixtures.
    #[serde(default)]
    pub oracle: OracleInfo,
    /// One entry per fixture file, sorted by path.
    #[serde(default, rename = "file")]
    pub files: Vec<Entry>,
}

/// The oracle build that generated the fixtures.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OracleInfo {
    /// The pinned wheel, e.g. `opencolorio==2.5.2`.
    #[serde(default)]
    pub package: String,
}

/// One fixture file.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Entry {
    /// Path relative to `fixtures/`, with `/` separators.
    pub path: String,
    /// Lowercase hex SHA-256 of the file's bytes.
    pub sha256: String,
    /// The oracle command that generated it.
    pub generator: String,
    /// The OCIO version the oracle reported.
    pub ocio_version: String,
    /// The machine that generated it (OS, CPU, features). Text fixtures must not depend on
    /// it; pixel data is never committed.
    pub machine: String,
}

impl Manifest {
    /// Reads `fixtures/MANIFEST.toml`, or an empty manifest if there is none yet.
    pub fn load() -> Result<Manifest, String> {
        let path = paths::fixtures_dir().join("MANIFEST.toml");
        match std::fs::read_to_string(&path) {
            Ok(text) => toml::from_str(&text).map_err(|e| format!("{}: {e}", path.display())),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Manifest::default()),
            Err(e) => Err(format!("{}: {e}", path.display())),
        }
    }

    /// Entries by path.
    pub fn by_path(&self) -> BTreeMap<&str, &Entry> {
        self.files.iter().map(|e| (e.path.as_str(), e)).collect()
    }
}

/// Lowercase hex SHA-256 of `bytes`.
pub fn sha256_hex(bytes: &[u8]) -> String {
    Sha256::digest(bytes)
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

fn manifest() -> &'static Manifest {
    static MANIFEST: OnceLock<Manifest> = OnceLock::new();
    MANIFEST.get_or_init(|| Manifest::load().unwrap_or_else(|e| panic!("fixture manifest: {e}")))
}

/// Reads fixture `rel` (relative to `fixtures/`) after checking it against the manifest.
#[track_caller]
pub fn read(rel: &str) -> Vec<u8> {
    let entry = manifest()
        .files
        .iter()
        .find(|e| e.path == rel)
        .unwrap_or_else(|| panic!("fixture {rel} is not in fixtures/MANIFEST.toml; generate it with `cargo xtask oracle regen`"));
    let path = paths::fixtures_dir().join(rel);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    let actual = sha256_hex(&bytes);
    assert!(
        actual == entry.sha256,
        "fixture {rel} was modified after generation (sha256 {actual}, manifest {}); regenerate it with `cargo xtask oracle regen`",
        entry.sha256
    );
    bytes
}

/// Reads fixture `rel` as UTF-8 text, after checking it against the manifest.
#[track_caller]
pub fn read_text(rel: &str) -> String {
    String::from_utf8(read(rel)).unwrap_or_else(|_| panic!("fixture {rel} is not UTF-8"))
}

/// Paths of all fixtures under `prefix` (relative to `fixtures/`), sorted.
pub fn list(prefix: &str) -> Vec<String> {
    manifest()
        .files
        .iter()
        .filter(|e| e.path.starts_with(prefix))
        .map(|e| e.path.clone())
        .collect()
}
