// SPDX-License-Identifier: BSD-3-Clause
// Copyright Contributors to the OpenColorIO Project.

//! `oracle regen|check|info` and `fixtures verify`.

use std::path::Path;
use std::process::Command;

use ocio_testkit::fixtures::{Entry, Manifest, OracleInfo, sha256_hex};
use ocio_testkit::oracle::{Oracle, machine_description};
use ocio_testkit::paths;
use serde::Deserialize;

const ORACLE_PACKAGE: &str = "opencolorio==2.5.2";

#[derive(Deserialize)]
struct RegenOutput {
    generator: String,
    ocio_version: String,
    files: Vec<String>,
}

pub(crate) fn oracle_info() -> Result<(), String> {
    let info = Oracle::get().try_call("info", serde_json::json!({}), &[])?;
    println!(
        "{}",
        serde_json::to_string_pretty(&info.result).map_err(|e| e.to_string())?
    );
    println!("machine: {}", machine_description());
    Ok(())
}

fn run_regen(group: &str, out_dir: &Path) -> Result<RegenOutput, String> {
    let oracle = Oracle::get();
    let output = Command::new(oracle.python())
        .args(["-X", "utf8", "-m", "ocio_oracle", "regen", group])
        .arg(out_dir)
        .current_dir(paths::oracle_dir())
        .env_clear()
        .envs(std::env::vars_os().filter(|(k, _)| {
            let k = k.to_string_lossy();
            k != "OCIO" && !k.starts_with("OCIO_") && k != "PYTHONPATH"
        }))
        .env("PYTHONDONTWRITEBYTECODE", "1")
        .output()
        .map_err(|e| format!("could not run the oracle: {e}"))?;
    if !output.status.success() {
        return Err(format!(
            "oracle regen {group} failed:\n{}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    serde_json::from_slice(&output.stdout).map_err(|e| format!("oracle regen output: {e}"))
}

fn check_group_name(group: &str) -> Result<(), String> {
    if group.is_empty()
        || !group
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
    {
        return Err(format!("invalid fixture group name `{group}`"));
    }
    Ok(())
}

pub(crate) fn regen(group: &str) -> Result<(), String> {
    check_group_name(group)?;
    let fixtures = paths::fixtures_dir();
    let group_dir = fixtures.join(group);
    if group_dir.exists() {
        std::fs::remove_dir_all(&group_dir).map_err(|e| format!("{}: {e}", group_dir.display()))?;
    }
    let out = run_regen(group, &fixtures)?;

    let mut manifest = Manifest::load()?;
    let prefix = format!("{group}/");
    manifest.files.retain(|e| !e.path.starts_with(&prefix));
    let machine = machine_description();
    for rel in &out.files {
        if !rel.starts_with(&prefix) {
            return Err(format!(
                "group {group} wrote {rel} outside fixtures/{group}/"
            ));
        }
        let bytes = std::fs::read(fixtures.join(rel)).map_err(|e| format!("{rel}: {e}"))?;
        manifest.files.push(Entry {
            path: rel.clone(),
            sha256: sha256_hex(&bytes),
            generator: out.generator.clone(),
            ocio_version: out.ocio_version.clone(),
            machine: machine.clone(),
        });
    }
    manifest.files.sort_by(|a, b| a.path.cmp(&b.path));
    manifest.oracle = OracleInfo {
        package: ORACLE_PACKAGE.to_string(),
    };
    write_manifest(&manifest)?;
    println!("fixtures/{group}: {} files", out.files.len());
    Ok(())
}

fn write_manifest(manifest: &Manifest) -> Result<(), String> {
    let text = toml::to_string_pretty(manifest).map_err(|e| e.to_string())?;
    let header =
        "# Generated by `cargo xtask oracle regen`. Do not edit: CI verifies every hash.\n\n";
    std::fs::write(
        paths::fixtures_dir().join("MANIFEST.toml"),
        format!("{header}{text}"),
    )
    .map_err(|e| e.to_string())
}

pub(crate) fn check_all() -> Result<(), String> {
    let manifest = Manifest::load()?;
    let mut groups: Vec<&str> = manifest
        .files
        .iter()
        .filter_map(|e| e.path.split('/').next())
        .collect();
    groups.dedup();
    let failures: Vec<String> = groups.iter().filter_map(|g| check(g).err()).collect();
    if failures.is_empty() {
        Ok(())
    } else {
        Err(failures.join("\n"))
    }
}

pub(crate) fn check(group: &str) -> Result<(), String> {
    check_group_name(group)?;
    let tmp = paths::target_dir().join("oracle-check").join(group);
    if tmp.exists() {
        std::fs::remove_dir_all(&tmp).map_err(|e| e.to_string())?;
    }
    std::fs::create_dir_all(&tmp).map_err(|e| e.to_string())?;
    let out = run_regen(group, &tmp)?;
    let manifest = Manifest::load()?;
    let committed = manifest.by_path();
    let prefix = format!("{group}/");
    let mut problems = Vec::new();
    for rel in &out.files {
        let bytes = std::fs::read(tmp.join(rel)).map_err(|e| e.to_string())?;
        match committed.get(rel.as_str()) {
            None => problems.push(format!("{rel}: generated here but not committed")),
            Some(entry) if entry.sha256 != sha256_hex(&bytes) => {
                problems.push(format!(
                    "{rel}: differs from the committed fixture (generated on {})",
                    entry.machine
                ));
            }
            Some(_) => {}
        }
    }
    for path in committed.keys().filter(|p| p.starts_with(&prefix)) {
        if !out.files.iter().any(|f| f == path) {
            problems.push(format!("{path}: committed but not generated here"));
        }
    }
    if problems.is_empty() {
        println!(
            "fixtures/{group}: {} files identical on {}",
            out.files.len(),
            machine_description()
        );
        Ok(())
    } else {
        Err(format!(
            "fixtures/{group} differs on this machine:\n  {}",
            problems.join("\n  ")
        ))
    }
}

pub(crate) fn verify() -> Result<(), String> {
    let fixtures = paths::fixtures_dir();
    let manifest = Manifest::load()?;
    let listed = manifest.by_path();
    let mut problems = Vec::new();
    let on_disk: Vec<String> = crate::walk(&fixtures)
        .into_iter()
        .filter(|p| p != "MANIFEST.toml" && p != "README.md")
        .collect();
    for rel in &on_disk {
        match listed.get(rel.as_str()) {
            None => problems.push(format!("{rel}: not in the manifest")),
            Some(entry) => {
                let bytes = std::fs::read(fixtures.join(rel)).map_err(|e| e.to_string())?;
                if sha256_hex(&bytes) != entry.sha256 {
                    problems.push(format!("{rel}: hash differs from the manifest"));
                }
            }
        }
    }
    for path in listed.keys() {
        if !on_disk.iter().any(|p| p == path) {
            problems.push(format!("{path}: in the manifest but missing"));
        }
    }
    if problems.is_empty() {
        println!("fixtures: {} files verified", on_disk.len());
        Ok(())
    } else {
        Err(format!(
            "fixture verification failed:\n  {}",
            problems.join("\n  ")
        ))
    }
}
